main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  min_price: 10  # Minimum house price in dollars
  max_price: 350  # Maximum house price in dollars

data_check:
  kl_threshold: 0.1  # Kullback-Leibler threshold for data drift detection

modeling:
  test_size: 0.2  # Fraction of data to use for test
  val_size: 0.2  # Fraction of remaining data to use for validation
  random_seed: 42  # Seed for reproducibility
  stratify_by: "neighbourhood_group"  # Column to use for stratification
  max_tfidf_features: 5  # Max features for TFIDF on the "name" column

  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1  # Use all available cores
    criterion: squared_error
    max_features: 0.5
    oob_score: true  # Enable out-of-bag score
